# Generated by Django 4.1.7 on 2023-04-29 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='food/images/')),
                ('title', models.CharField(max_length=255)),
                ('food_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('tea', 'Tea'), ('dinner', 'Dinner')], max_length=20)),
                ('is_ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('tea', 'Tea'), ('dinner', 'Dinner')], max_length=20)),
                ('order_date', models.DateField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.viewfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
