# Generated by Django 4.1.7 on 2023-04-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewfood',
            old_name='is_ordered',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='food_type',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
