# Generated by Django 4.1.7 on 2023-04-29 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_is_ordered_viewfood_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2023, 4, 29)),
        ),
    ]
