# Generated by Django 4.1.7 on 2023-04-29 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_foodorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewfood',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
