# Generated by Django 4.1.7 on 2023-04-29 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_viewfood_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
