# Generated by Django 4.1.7 on 2023-05-02 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_foodorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2023, 5, 2)),
        ),
    ]
